name: CI
on: [push]

jobs: 
  build: 
    name: "Build nb-javac"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 25
        uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: '25'

      - name: Build JARs
        # This will now include your javax and com.sun tools based on your edits
        run: ant -f make/langtools/netbeans/nb-javac clean jar

      - name: Verify with build-jdk.sh
        # Keeps the logic for stripping module hashes and testing the image
        run: |
          chmod +x ./build-jdk.sh
          JAVA_HOME_VERSION=$JAVA_HOME ./build-jdk.sh

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: nb-javac-artifacts
          path: make/langtools/netbeans/nb-javac/dist/*.jar
